---
- name: Configure networkmanager with dhcp_hostname
  hosts: "{{ vm_name }}"
  become: true
  tasks:
    - name: Option 1 - Write NetworkManager Template
      ansible.builtin.template:
        src: ../templates/networkmanager.config.j2
        dest: /etc/sysconfig/...
    - name: Option 2 - Ensure dhcp hostname is present in NM Config
      ansible.builtin.lineinfile:
        backup: true
        search_string: DHCP_HOSTNAME=
        line: DHCP_HOSTNAME={{ vm_name }}
        state: present